"""Add first_name and last_name to a User model

Revision ID: c494d82508f1
Revises: 5515466da969
Create Date: 2024-06-23 05:50:23.634175

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c494d82508f1'
down_revision = '5515466da969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Commented out the drop_table operation for sysdiagrams
    # op.drop_table('sysdiagrams')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # Commented out the create_table operation for sysdiagrams
    # op.create_table('sysdiagrams',
    # sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    # sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    # sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B6107DFDEC1')
    # )
    # ### end Alembic commands ###
